services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: note-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
      - DB_NAME=note-web
      - DB_USER=postgres
      - DB_PWD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"

volumes:
  postgres_data: